baseURL = "https://kaios.dev"
languageCode = "en-us"
title = "KaiOS.dev"

theme = "puppet"
useFaviconGenerator = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true

copyright = "Copyright Â© 2023-2025. Last Byte LLC"
defaultContentLanguage = "en"

[pagination]
  pagerSize = 8

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

[outputs]
  home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    noClasses = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    style = "dracula"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100
  [[menu.main]]
    identifier = "getting-started"
    name = "Getting Started"
    url = "/series/getting-started/"
    weight = 20
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
  [[menu.main]]
    identifier = "privacy"
    name = "Privacy"
    url = "/privacy/"
    weight = 50

relativeURLs = false
refLinksErrorLevel = "WARNING"

[permalinks]
  posts = '/:year/:month/:title/'

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = true
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      noNullishOperator = false
      precision = 0

[params]
  tagsLimit = 20
  description = "Build modern experiences on KaiOS mobile phones"
  keywords = "KaiOS,developer,blog,software,guide,web,mobile,JavaScript,CSS,HTML,Firefox"
  img_home = "img/home-alt.png"
  img_404 = "img/404-bg.jpg"

[params.author]
  name = "Tom Barrasso"
  url = "https://tombarrasso.com"

## llms.txt
[params.robots]
  llmsTXT = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[params.social]
  rss = true
  github = "Tombarr"
  linkedin = "tombarrasso"

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
  enable = true
  # Overwritten by your gravatar image if `gravatarEmail` is filled
  avatar = "/img/tom-barrasso.jpg"
  bio = "Tom Barrasso was the Head of Developer Relations at CloudMosa and founder of PodLP, the first podcast app for KaiOS, the JioPhone, and Cloud Phone with 10M+ installs in over 175 countries."

[params.giscus]
  enable = false
